### PR TITLE
Functions for interacting with objects created by student code

### LINKED ISSUE #268: Grading based on object(s) in `.result` and `.solution`
In this exercise student is guided to build a linear regression model and save it as object named `model1`. 

The solution code to the exercise looks like this:
`model1 <- lm(dist~speed, data = cars)`

**Instead of comparing just the input code from the user and the solution, I would want to check if the `model1` created in the exercise chunk (by the user) is equivalent to the `model1` in the solution.**

Grading would possibly work this way:
`pass_if(identical(get(model1, .result), get(model2, .solution)) `

Or somehow else. 

Importantly, it would be great to be able to get the objects constructed in the exercise and compare it to the object in the solution. If this is already possible, please let me know.

### LINKED ISSUE #291: Helper function to find object in `.envir_result`
Occasionally grading authors need to find objects that should have been created by submitted code. There are several base-R functions that can help with this process, but we could provide a nicer interface around the interaction.

``` r
pkgload::load_all()
#> ℹ Loading gradethis
library(dplyr, warn.conflicts = FALSE)

ex <- mock_this_exercise({
  mtcars_table <- as_tibble(mtcars)
  mtcars_cyl_6 <- mtcars_table[mtcars_table$cyl == 6, ]
})
```

The user created the `mtcars_cyl_6` object…

``` r
exists("mtcars_cyl_6", ex$.envir_result, inherits = FALSE)
#> [1] TRUE
```

…but we expected `mtcars_tbl`.

``` r
exists("mtcars_tbl", ex$.envir_result, inherits = FALSE)
#> [1] FALSE
```

Here’s everything in the user result env:

``` r
ls(ex$.envir_result)
#> [1] "mtcars_cyl_6" "mtcars_table"
```

What’s a possible match?

``` r
agrep("mtcars_tbl", ls(ex$.envir_result), value = TRUE)
#> [1] "mtcars_table"
```

### PR DESCRIPTION
**Pull request by rossellhayes**
* `user_object_get()` returns an object created by the student's code.
* `user_object_exists()` checks if an object was created by the student's code.
* `user_object_list()` lists objects created by the student's code.
* `solution_object_get()` returns an object created by the solution code.
* `solution_object_exists()` checks if an object was created by the solution code.
* `solution_object_list()` lists objects created by the solution code.

Closes #291 and closes #268.

This PR also introduces the `with_exercise()` helper function, which runs an expression as if it were in an exercise's `grade_this()` block.
This function is primarily useful for running gradethis functions outside the context of a learnr tutorial, e.g. for examples or testing.

### CODE REVIEW

**Comment by rossellhayes** [comment]
Test failures will be fixed by #334.

File: R/user_object.R [hunk 1]
```diff
@@ -0,0 +1,116 @@
...
+
+    objects <- setdiff(objects, exclude_objects)
+  }
+
+  objects
+}
+
+#' @rdname user_object
+#' @export
+solution_object_get <- function(
```
Comment (nischalshrestha) [inline R/user_object.R:80]: Question: is `.solution` not yet evaluated until any one of these `solution_object_*()` are called or a `force(.solution)`?

File: R/user_object.R [hunk 2]
```diff
@@ -0,0 +1,116 @@
...
+  x, mode = "any", ..., gradethis_env = parent.frame()
+) {
+  resolve_placeholder(.solution, gradethis_env)
+  user_object_get(
```
Comment (nischalshrestha) [inline R/user_object.R:84]: I wonder if we should have a more basic `object_get()` where we then pass in the appropriate `envir`? This slightly confused me at first since it was a call to `user_object_get()`

File: R/gradethis_exercise_checker.R [hunk 3]
```diff
@@ -307,6 +307,8 @@ prepare_check_env <- function(
     check_env[[".solution_code"]] <- solutions[[length(solutions)]]
   }
 
+  check_env[[".envir_solution"]] <- envir_base
```
Comment (nischalshrestha) [inline R/gradethis_exercise_checker.R:310]: Exciting! 🚀

File: R/user_object.R (hunk 1 above)
Comment (rossellhayes) [reply R/user_object.R:80]: That's right, when we enter `grade_this()`, the `-solution` chunk has not yet been evaluated. Resolving `.solution` here ensures that it's evaluated so that we can check its environment for objects. If the author happened to call a function that uses `.solution` earlier in their grading code, then resolving it here just does nothing.

File: R/user_object.R (hunk 2 above)
Comment (rossellhayes) [reply R/user_object.R:84]: That seems like a good idea to me! I think it makes sense to just make those internal functions, right? Since I can't really see a use case for a generic `object_get()` that's not already covered by `user_object_get()`, `solution_object_get()`, or just plain old `get()`.

Comment (nischalshrestha) [reply R/user_object.R:84]: Yeah that's exactly what I was thinking of, make it more internal that these public ones call.
