### PR TITLE
Make hints more consistent

### LINKED ISSUE #243: Global fail.hint = TRUE + fail() = doubled hints
When I run the tutorial below, I receive a duplicated code hint in the feedback message. We should change this to a single code hint.

````
---
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
library(gradethis)

gradethis_setup(
  fail.hint = TRUE,      # Give a code feedback hint on all fail*()? Remove if not desired
  fail.encourage = TRUE, # Encourage on all fail*()
  pass.praise = TRUE     # Praise on all pass*()
)
```

Type 1.


```{r yo, exercise = TRUE}

```

```{r yo-solution}
1
```

```{r yo-check}
grade_this({
  pass_if_equal()
  fail()
})
```

````

Screen Shot 2021-06-02 at 11 56 48 AM

If I add `hint = FALSE` to `fail()`, the feedback is reduced to a single code hint.

````
---
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
library(gradethis)

gradethis_setup(
  fail.hint = TRUE,      # Give a code feedback hint on all fail*()? Remove if not desired
  fail.encourage = TRUE, # Encourage on all fail*()
  pass.praise = TRUE     # Praise on all pass*()
)
```

Type 1.


```{r yo, exercise = TRUE}

```

```{r yo-solution}
1
```

```{r yo-check}
grade_this({
  pass_if_equal()
  fail(hint = FALSE)
})
```

````

Screen Shot 2021-06-02 at 11 57 06 AM

### PR DESCRIPTION
**Pull request by gadenbuie**
Fixes #243

We had a few inconsisntencies in how hints -- a.k.a. code feedback -- were added to feedback messages.

We effectively have many methods of adding hints:

- Actively in the message template: `fail("{maybe_code_feedback()}")`
- Semi-actively in the default message template: `gradethis_setup(fail = "{maybe_code_feedback()}")`
- Actively suppressing the hint in the call to `fail()` with a default message: `fail(hint = FALSE)`
- Passively in the call to `fail()` with a non-default message: `fail("Not quite.", hint = TRUE)`
- Extra-passively with the global option: `gradethis_setup(fail.hint = TRUE)`

This PR favors earlier active methods over later passive methods and ensures that feedback is only added once. The feedback template string is seens as the most "active" way to signal an intent to include code feedback. 

In all circumstances, when `hint = TRUE` (either locally or globally), the hint will appear where `"{maybe_code_feedback()}"` appears in the template string, or at the end if not part of the template.

If `"{maybe_code_feedback()}"` appears in the default fail feedback message, then code feedback will always appear unless the user explicitly sets `hint = FALSE`.

The full behavior with the interaction of all possible options is covered in `test-code_feedback.R`.

### CODE REVIEW

File: R/graded.R [hunk 1]
```diff
@@ -252,8 +252,23 @@ fail <- function(
   hint = getOption("gradethis.fail.hint", FALSE),
   encourage = getOption("gradethis.fail.encourage", FALSE)
 ) {
+  user_provided_hint <- !missing(hint)
+  user_provided_message <- !missing(message)
```
Comment (schloerke) [inline R/graded.R:256]: Should we use `rlang::missing_arg()` instead?

And have the "arg is missing" value be the respective `getOption()` call above

Comment (gadenbuie) [reply R/graded.R:256]: I considered that (and I think we'd also be fine with a sentinel `NULL` here), but I think it somewhat obscures the default value or how the default value is determined.

I think I'd rather add a helper for looking up global default values, e.g. `gradethis_default()`

```r
fail <- function(
  message = gradethis_default("fail"),
  ...,
  hint = gradethis_default("fail.hint"),
  encourage = gradethis_default("fail.encourage")
) { ... }
```

where the documentation can better direct users to `gradethis_setup()` (they'd be in the same help page) where those values are set.

Internally, `gradethis_default()` could add an `attr()` that we could use in cases like this while still keeping the default values in the function signature.

Comment (gadenbuie) [reply R/graded.R:256]: Btw, I'm envisioning the above as a separate chunk of work 😄

Comment (schloerke) [reply R/graded.R:256]: Given that is on a list somewhere, sounds good.

**Review by schloerke — APPROVED** [review]

File: R/graded.R (hunk 1 above)
Comment (gadenbuie) [reply R/graded.R:256]: https://github.com/rstudio/gradethis/issues/245
