### PR TITLE
Fix error when `.user_code` is empty

### LINKED ISSUE #262: `grade_this_code()` returns an error if `.user_code` is empty
Possibly related to #13.

If a student submits an empty code chunk, `grade_this_code()` returns a neutral grade with an error. I would have expected either a failing grade or a neutral grade with a message explaining that the submission was empty. At the very least, the student should not see an error and the message should not state that there was a problem with the grading code.

``` r
library(gradethis)

grade_this_code()(
  mock_this_exercise(.user_code = "", .solution_code = "rnorm(1)")
)
#> #> grade_this_code()(mock_this_exercise(.user_code = "", .solution_code = "rnorm(1)"))
#> Error in (function (e) {    on_error(e, this_env)})(structure(list(message = "Assertion on 'user_code' failed: All elements must have at least 1 characters.",     call = to_expr(user_code, "user_code")), class = c("simpleError", "error", "condition"))): Assertion on 'user_code' failed: All elements must have at least 1 characters.
#> <gradethis_graded_this_code: [Neutral]
#>   A problem occurred with the grading code for this exercise.
#> >
```

<sup>Created on 2021-10-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### PR DESCRIPTION
**Pull request by rossellhayes**
`grade_this()` and `grade_this_code()` now give neutral feedback with no error if `.user_code` is empty.

Closes #262.

``` r
library(gradethis)

grade_this_code()(
  mock_this_exercise(.user_code = "", .solution_code = "rnorm(1)")
)
#> <gradethis_graded: [Neutral]
#>   I didn't receive your code. Did you write any?
#> >

grade_this({fail(hint = TRUE)})(
  mock_this_exercise(.user_code = "", .solution_code = "rnorm(1)")
)
#> <gradethis_graded: [Neutral]
#>   I didn't receive your code. Did you write any?
#> >
```

<sup>Created on 2022-02-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### CODE REVIEW

File: R/grade_this.R [hunk 1]
```diff
@@ -269,6 +270,26 @@ NULL
...
+
+  if (is.null(user_code) || length(user_code) == 0 || !nzchar(user_code)) {
+    rlang::return_from(
+      frame,
+      graded(
+        logical(),
+        "I didn't receive your code. Did you write any?",
+        type = "info"
+      )
+    )
```
Comment (gadenbuie) [inline R/grade_this.R:287]: Let's use standard returns here and rely on capturing the graded condition if we want to exit early. One idea would be to call `graded()` and then return `""` if bad user code, otherwise return the discovered `user_code`.

In calling functions we can rely on `capture_graded()` or `tryCatch()` or even `ignore_graded()` to choose how to handle the graded condition.

File: R/grade_this.R [hunk 2]
```diff
@@ -269,6 +274,24 @@ NULL
 #' @export
 .user_code <- placeholder(".user_code")
 
+empty_code <- function(code, check_null = FALSE) {
```
Comment (gadenbuie) [inline R/grade_this.R:277]: I think this function is trying to do too much. Instead of testing for empty code _and_ creating the empty code grade, I think we should do it in two steps.

```r
check_is_code_empty <- function(code, check_null) {
  # returns TRUE or FALSE
}

grade_code_is_empty <- function(...) {
  graded(logical(), "message", type = "info")
}
```

so you would use it like

```r
if (check_is_code_empty(user_code)) {
  return(grade_code_is_empty())
}
```

Comment (gadenbuie) [reply R/grade_this.R:277]: Those two functions should be higher up, perhaps under `detect_grade_this()`, since this section covers the placeholder objects.

File: R/grade_this.R [hunk 3]
```diff
@@ -269,6 +274,24 @@ NULL
...
+  if (check_null) {
+    empty_code <- is.null(code) || length(code) == 0 || !nzchar(code)
+  } else {
+    empty_code <- length(code) && !nzchar(code)
+  }
```
Comment (gadenbuie) [inline R/grade_this.R:282]: Having a function just for checking for empty code lets you simply the logic using early returns.

```suggestion
  if (isTRUE(check_null) && is.null(code)) {
    return(TRUE)
  }
  
  length(code) == 0 || !nzchar(code)
```

or maybe the non-NULL empty code test should be


```suggestion
  if (isTRUE(check_null) && is.null(code)) {
    return(TRUE)
  }
  
  length(code) == 0 || all(!nzchar(trimws(code)))
```

File: R/grade_this.R [hunk 4]
```diff
@@ -142,6 +142,11 @@ grade_this <- function(
       check_env <- list2env(check_env, envir = new.env(parent = emptyenv()))
     }
 
+    empty_code <- empty_code(check_env[[".user_code"]])
+    if (!is.null(empty_code)) {
+      return(empty_code)
+    }
+
```
Comment (gadenbuie) [inline R/grade_this.R:149]: Maybe `grade_this()` shouldn't be strict about empty code? We don't _know_ that we're going to need the user code yet ... whereas `grade_this_code()` and `fail_if_code_feedback()` require code _a priori_.

File: R/grade_this.R (hunk 2 above)
Comment (rossellhayes) [reply R/grade_this.R]: Split and relocated in [033315d](https://github.com/rstudio/gradethis/pull/288/commits/033315de49b6da55ef73c1f79916c30d7ed79774)

File: R/grade_this.R (hunk 3 above)
Comment (rossellhayes) [reply R/grade_this.R]: Since the `check_null` argument is only `TRUE` in one place, I just moved the logic out of the function altogether in [451763c](https://github.com/rstudio/gradethis/pull/288/commits/451763c4f9ff99ae55e906cb34de3b25066913be)

File: R/grade_this.R (hunk 4 above)
Comment (rossellhayes) [reply R/grade_this.R]: That's a good point. Changed in [6bd364a](https://github.com/rstudio/gradethis/pull/288/commits/6bd364a60343fd898195bffc0de645e04f526db9)

File: R/graded.R [hunk 5]
```diff
@@ -644,10 +644,12 @@ fail_if_code_feedback <- function(
...
     user_code <- get_from_env(".user_code", env)
     assert_object_found_in_env(user_code, env, "fail_if_code_feedback")
-    if (is.null(user_code) || length(user_code) == 0 || !nzchar(user_code)) {
-      graded(logical(), "I didn't receive your code. Did you write any?", type = "info")
-    }
   }
+
+  if (length(user_code) == 0 || is_empty_code(user_code)) {
+    return(grade_code_is_empty())
+  }
```
Comment (gadenbuie) [inline R/graded.R:651]: Did you mean to check if `user_code` is NULL here?

```suggestion
  if (is.null(user_code) || is_empty_code(user_code)) {
    return(grade_code_is_empty())
  }
```

File: R/grade_this.R (hunk 3 above)
Comment (gadenbuie) [reply R/grade_this.R]: Yeah and `length(NULL) == 0` so we'll catch it anyway.

`str_trim()` is a good idea, but we only officially support back to 3.4.

File: R/graded.R (hunk 5 above)
Comment (gadenbuie) [reply R/graded.R:651]: Actually `is_empty_code(NULL)` should also return `TRUE`, so that's probably all you need here.

File: R/grade_this.R (hunk 3 above)
Comment (gadenbuie) [reply R/grade_this.R]: Testing locally, I changed `is_empty_code()` to

```r
is_empty_code <- function(code) {
  length(code) == 0 || all(!nzchar(str_trim(code)))
}
```

and no tests failed. Reading between the lines, I think that when we were including this test in `grade_this()` it would have made sense to allow `.user_code` to be `NULL` since we might not want to be overly restrictive. But now that we're applying the test in a more targeted way for just `grade_this_code()` and `fail_if_code_feedback()`, it's okay for `is_empty_code()` to be a little more general.

Comment (gadenbuie) [reply R/grade_this.R]: I made the change above in [2fce7b5](https://github.com/rstudio/gradethis/pull/288/commits/2fce7b57cfe7f417714ee9f39168d453b1ea70d4) and then moved `grade_code_is_empty()` to `grade_this_code.R` in [61a2919](https://github.com/rstudio/gradethis/pull/288/commits/61a2919e78476e3622992d1e60c6de7fb4481317). I'm going to merge this to unblock other PRs but if I've misunderstood something we can fix it in a new PR.

**Review by gadenbuie — APPROVED** [review]
Thank you! 🚀 🌔

File: R/grade_this.R (hunk 3 above)
Comment (rossellhayes) [reply R/grade_this.R]: > I think that when we were including this test in `grade_this()` it would have made sense to allow `.user_code` to be `NULL`

Yeah, when the check happened in `grade_this()`, it caused a lot of test failures because a lot of the tests for `grade_this()` didn't define `.user_code`. Now that `is_empty_code()` is only called when code checking is going to happen, I think it makes sense to check if the code is an empty string _or_ `NULL`.
