### PR TITLE
Avoid duplication of hint for failing grades in `grade_this_code()`

### LINKED ISSUE #324: `grade_this_code()` duplicates feedback when `gradethis_setup(fail.hint = TRUE)`
When `gradethis_setup(fail.hint = TRUE)`, `grade_this_code()` provides the same feedback twice when given an incorrect answer. This is most likely because `grade_this_code()` internally calls two functions that can generate feedback: `code_feedback()` and `fail()`.

``` r
library(gradethis)
ex <- mock_this_exercise(.user_code = "sqrt(log(2))", .solution_code = "sqrt(log(1))")

gradethis_setup(fail.hint = FALSE)
grade_this_code()(ex)
#> <gradethis_graded_this_code: [Incorrect]
#>   In `log(2)`, I expected `1` where you wrote `2`. That's okay: you
#>   learn more from mistakes than successes. Let's do it one more time.
#> >

gradethis_setup(fail.hint = TRUE)
grade_this_code()(ex)
#> <gradethis_graded_this_code: [Incorrect]
#>   In `log(2)`, I expected `1` where you wrote `2`. Try it again. You
#>   get better each time. In `log(2)`, I expected `1` where you wrote
#>   `2`.
#> >
```
<sup>Created on 2022-09-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

## Possible solution
`grade_this_code()` could internally call `fail(hint = FALSE)` to ensure that `fail()` never generates a duplicate message.

### PR DESCRIPTION
**Pull request by rossellhayes**
Update `grade_this_code()` to call `fail()` with `hint = FALSE` to ensure hint isn't duplicated.

Closes #324.

# Before

``` r
ex <- mock_this_exercise(.user_code = "2", .solution_code = "1")
gradethis_setup(fail.hint = TRUE)

grade_this_code()(ex)
#> <gradethis_graded_this_code: [Incorrect]
#>   I expected `1` where you wrote `2`. That's okay: you learn more from
#>   mistakes than successes. Let's do it one more time. I expected `1`
#>   where you wrote `2`.
#> >
```

# After

```r
ex <- mock_this_exercise(.user_code = "2", .solution_code = "1")
gradethis_setup(fail.hint = TRUE)

grade_this_code()(ex)
#> <gradethis_graded_this_code: [Incorrect]
#>   I expected `1` where you wrote `2`. But no need to fret, try it
#>   again.
#> >
```

<sup>Created on 2022-10-03 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

**Review by gadenbuie — COMMENTED** [review]
We need a test or two around this that would have caught the unexpected behavior in #324. While in there, it'd also be good to ensure all permutations of hint behavior for `grade_this_code()` are covered in our tests.

**Comment by rossellhayes** [comment]
@gadenbuie Thoughts on these tests?

File: R/staticimports.R [hunk 1]
```diff
@@ -81,3 +81,35 @@ str_extract <- function(text, pattern) {
...
 }
+# Generated by staticimports; do not edit by hand.
+# ======================================================================
+# Imported from pkg:stringstatic
+# ======================================================================
+
+`%||%` <- function(lhs, rhs) {
+  if (length(lhs) == 0) return(rhs)
+  lhs
+}
```
Comment (gadenbuie) [inline R/staticimports.R:92]: This could be a problem https://github.com/rstudio/gradethis/blob/c1e0c978078036a4a3341240be8377d3462c221c/R/gradethis-package.R#L10

File: R/staticimports.R [hunk 2]
```diff
@@ -81,3 +81,35 @@ str_extract <- function(text, pattern) {
...
+  structure(
+    pattern,
+    options = list(case_insensitive = ignore_case),
+    class = c("fixed", "pattern", "character")
+  )
+}
+
+str_count <- function(string, pattern) {
+  is_fixed <- inherits(pattern, "fixed")
+  ignore.case <- attr(pattern, "options")$case_insensitive %||% FALSE
```
Comment (gadenbuie) [inline R/staticimports.R:104]: I'd recommend you rewrite the static export to avoid `%||%`, it'd be more portable that way and only a little more verbose.

**Review by gadenbuie — COMMENTED** [review]
Looks good, but are you sure you've covered all of the options that might affect printing of code feedback from `grade_this_code()`?

File: R/staticimports.R (hunk 2 above)
Comment (rossellhayes) [reply R/staticimports.R]: Good thinking! All it took was an `isTRUE()`, which is much more elegant if I do say so myself [281f2ae](https://github.com/rstudio/gradethis/pull/325/commits/281f2ae708e1ddf20b6f7d4f2b1ce6ab5e0d87c7)

**Comment by rossellhayes** [comment]
> Looks good, but are you sure you've covered all of the options that might affect printing of code feedback from `grade_this_code()`?

I added some tests that vary the `maybe_code_feedback` option, but I don't think that affects the `grade_this_code()` output even without this PR. Is that what you had in mind?

The only option I could see besides `fail.hint` that affects `grade_this_code()` output is `fail.encourage`, but that doesn't seem relevant to this issue.

**Comment by gadenbuie** [comment]
The only thing I can think of that isn't covered is the case where `grade_this_code()` fails but doesn't include any feedback, which should be possible by modifying the `incorrect` message.

Actually, we should also add coverage for using `maybe_code_feedback()` instead of `code_feedback()` in the incorrect message.

**Comment by rossellhayes** [comment]
@gadenbuie I think this should be ready to go now 🤞

File: tests/testthat/test-grade_this_code.R [hunk 3]
```diff
@@ -191,3 +191,60 @@ test_that("grade_this_code() doesn't have to return a grade", {
...
+  )
+
+  expect_equal(
+    grade_this_code(incorrect = "incorrect")(ex)$message,
+    "incorrect"
+  )
+
+  # Add documentation for how to not include code feedback.
+  # - in incorrect argument
+  # - in description when talking about customizable incorrect message
```
Comment (gadenbuie) [inline tests/testthat/test-grade_this_code.R:249]:
```suggestion
```

**Review by gadenbuie — APPROVED** [review]
Thanks for tracking down all the loose ends! 🧶
