### PR TITLE
If `waldo::compare()` errors, fall back to `identical()`

### LINKED ISSUE #328: Unexpected error in `pass_if_equal()`
🕵️‍♂️ Investigating this bug spotted by @nischalshrestha 

```r
library(gradethis)

.result <- structure(c(`0` = 0.0160069994947357, `1` = -0.0954295831831162, 
                       `2` = -0.060342605088278, `3` = 0.0993515771117325, `4` = 0.101717325946816
), .Dim = 5L, .Dimnames = list(c("0", "1", "2", "3", "4")))

.solution <- structure(c(`0` = 1.53731223147442, `1` = -9.16505716890648, 
                         `2` = -5.79530379267822, `3` = 9.54172546581079, `4` = 9.76893198393223
), .Dim = 5L, .Dimnames = list(c("0", "1", "2", "3", "4")))

gradethis::pass_if_equal()
#> Warning: Error in grade_if_equal(): names(lines) <- format(c("", row_idx), align
#> = "right"): 'names' attribute [11] must be the same length as the vector [3]
#> <gradethis_graded: [Neutral]
#>   A problem occurred with the grading code for this exercise.
#> >
```

### PR DESCRIPTION
**Pull request by rossellhayes**
Avoids errors when in `grade_if_equal()` resulting in ungraded code when `.result` or `.solution` cannot be properly handled by `waldo::compare()`.

Closes #328:

``` r
.result <- structure(c(`0` = 0.0160069994947357, `1` = -0.0954295831831162, 
                       `2` = -0.060342605088278, `3` = 0.0993515771117325, `4` = 0.101717325946816
), .Dim = 5L, .Dimnames = list(c("0", "1", "2", "3", "4")))

.solution <- structure(c(`0` = 1.53731223147442, `1` = -9.16505716890648, 
                         `2` = -5.79530379267822, `3` = 9.54172546581079, `4` = 9.76893198393223
), .Dim = 5L, .Dimnames = list(c("0", "1", "2", "3", "4")))

pass_if_equal()
#> NULL
```

<sup>Created on 2022-12-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

File: R/graded.R [hunk 1]
```diff
@@ -564,25 +564,26 @@ grade_if_equal <- function(
...
-        "different"
-      } else if (grepl("reached theoretically unreachable branch 2", e$message, fixed = TRUE)) {
-        "different"
-      } else {
-        warning(
-          "Error in grade_if_equal(): ", deparse(e$call), ": ", e$message, call. = FALSE
-        )
-        capture_graded(grade_grading_problem(error = e))
-      }
+      # these cases as simply "different" if they aren't identical.
```
Comment (gadenbuie) [inline R/graded.R:585]: Very minor edits to the comment:

```r
      # waldo::compare() takes into account a lot of the things we'd have to
      # think about in comparing two objects, but its goal is to create a
      # readable diff. Since we're engaging in some off-label usage of these
      # functions, they will sometimes error or take longer than desired when we
      # give them unusual inputs. In these cases, we fall back to `identical()`.
      # Since we aren't (currently) interested in reporting the differences
      # between `x` and `y`, we mark them "different" if they aren't identical.
```

File: R/graded.R [hunk 2]
```diff
@@ -564,25 +564,26 @@ grade_if_equal <- function(
   local_options_waldo_compare()
 
   compare_msg <- tryCatch(
-    waldo::compare(x, y, tolerance = tolerance),
+    {
+      time_limit <- knitr::opts_chunk$get("exercise.timelimit") %||%
+        gradethis_default_learnr_options$exercise.timelimit
+      time_limit <- time_limit * 0.8
```
Comment (gadenbuie) [inline R/graded.R:570]: I think we should maybe have a gradethis-specific option whose default is `exercise.timelimit * 0.8`?

Comment (rossellhayes) [reply R/graded.R:570]: That makes sense! Because naming things is hard™, did you have an idea in mind? Would it be something like `gradethis.timelimit`, or more specific like `gradethis.waldo.timelimit`?

File: R/graded.R (hunk 1 above)
Comment (rossellhayes) [reply R/graded.R:585]: Very well put!

File: R/graded.R (hunk 2 above)
Comment (nischalshrestha) [reply R/graded.R:570]: I'm liking the specific `gradethis.waldo.timelimit` since this is a time limit set for the `waldo::compare()`? But, if you wanted to be more generic maybe `gradethis.compare.timelimit` (in case  we didn't want to use `waldo` anymore or something)

Comment (rossellhayes) [reply R/graded.R]: I implemented it in [7986e76](https://github.com/rstudio/gradethis/pull/329/commits/7986e763388815b4de0547e365ed721d804630ef) as `diff.timelimit` (just to keep our options open in case we want to use `diffobj` or something instead of `waldo` in the future)

**Comment by rossellhayes** [comment]
> Thanks for working on this! One minor thing I noticed while testing this change with the above code example, I get an error message after waiting for > 30s (maybe it's the 80% of time limit):
> 
> ```
> >   pass_if_equal()
> NULL
> Error: reached elapsed time limit
> ```
> 
> I'm guessing whatever timer is keeping track is not interrupted/exited when `pass_if_equal()` returns?

Playing around within a tutorial, it looks like that error message _does_ get printed to the console about half the time, but subsequent grading code still runs successfully after the message. I think since `setTimeLimit()` is called within a `tryCatch()` it suppresses the early exit, but for some reason it doesn't suppress the message. @gadenbuie, does that sound plausible?

File: R/graded.R (hunk 2 above)
Comment (gadenbuie) [reply R/graded.R]: My naming convention here (and in general) for options that serve as default values of arguments is to use `<package>.<function>.<argument>`. This is a little tricky since we don't export `grade_if_equal()`, so my preference is `gradethis.compare_if_equal.timelimit`. 

Or, since this isn't directly attached to an argument of an exported function, we could go for symmetry with the learnr's `exercise.timlimit` option and use `gradethis.compare_timelimit`.

**Comment by gadenbuie** [comment]
It's not clear from the documentation, but the timelimit needs to be reset (AFAICT this is required when the time-limited computation succeeds, otherwise subsequent computations become part of the elapsed time measurement). I added `try_with_timelimit()`, which wraps the computation and restores the timelimit on exit. It also throws a classed error if the time limit is exceeded (not that we need to use that right now but it might be helpful in the future).

I _didn't_ change the name of the option, but after thinking on this a bit I think my preference is `gradethis.compare_timelimit`.

**Comment by rossellhayes** [comment]
@gadenbuie Option name is updated!

**Review by gadenbuie — APPROVED** [review]
LGTM!
